# -*- encoding: utf-8 -*-
from . import efficient_report
from . import production_by_hours_report
from . import interruptions_by_section_report
from . import interruptions_by_line_report
from . import interruptions_by_machine_report
from . import efficiency_accomplish_report
from . import prod_and_reg_amf_report
from . import interruptions_to_excel_report
from . import time_use_to_excel_report
from . import efficiency_cdt_excel_report
#from . import resume_time_frequency_report
from . import compliance_planned_efficiency
from . import compliance_planned_cdt
from . import machine_set_of_peaces_report
from . import bd_production_hours_report
from . import statistical_results_report
from . import production_rejection_report
from . import resume_time_frequencyn_report
