services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UNAME: ${USER:-developer}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: odoo-18.0
    depends_on:
      - db
    environment:
      # Debugger
      - DEBUGPY_ENABLE=true
      - DEBUGPY_PORT=5678
      # PostgreSQL
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"  # Odoo web
      - "5678:5678"  # Debugger
    # volumes:
      # - ./config:/etc/odoo
      # - ./extra-addons:/mnt/extra-addons
    # command: ["--dev=all"] # ["--dev=reload,xml,qweb"]
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./addons
    #       target: /mnt/extra-addons
    tty: true

  db:
    image: postgres:17
    container_name: odoo-db-18.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data