services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        IMAGE_TAG: ${IMAGE_TAG}
        UNAME: ${USER:-developer}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: odoo-${CONTAINER_NAME}
    depends_on:
      - db
    environment:
      # PostgreSQL
      - HOST=db
      - PORT=5432
      - USER=${CONTAINER_USER}
      - PASSWORD=${CONTAINER_PASSWORD}
      # Debugger
      # - DEBUGPY_ENABLE=true
      # - DEBUGPY_PORT=5678
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      - ./enterprise-addons:/mnt/enterprise-addons
    ports:
      - "8069:8069"  # Odoo web
      - "5678:5678"  # Debugger
      - "8072:8072"  # Web socket
    command: --dev=all --update=ict
    tty: true

  db:
    image: postgres-backup:${IMAGE_TAG}
    container_name: db-${CONTAINER_NAME}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${CONTAINER_USER}
      - POSTGRES_PASSWORD=${CONTAINER_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-odoo-data:/var/lib/postgresql/data

  pgadmin:
    image: pgadmin4:15
    container_name: pg-${CONTAINER_NAME}
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${CONTAINER_PASSWORD}
    volumes:
      - pgadmin-odoo-data:/var/lib/pgadmin

volumes:
  odoo-data:
    name: odoo-data-${VOLUME_NAME}
    external: true
  postgres-odoo-data:
    name: postgres-odoo-data-${VOLUME_NAME}
    external: true
  pgadmin-odoo-data:
    name: pgadmin-odoo-data-${VOLUME_NAME}