services:
  odoo:
    image: ${IMAGES_NAME}
    container_name: odoo_${CONTAINER_NAME}
    depends_on:
      - postgres
    environment:
      - HOST=db_${CONTAINER_NAME}
      - USER=${CONTAINER_USER}
      - PASSWORD=${CONTAINER_PASSWORD}
    ports:
      - "8017:8069"
      - "5679:5678"
    volumes:
#      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
    restart: unless-stopped
    tty: true
    entrypoint: /usr/bin/python3 -m debugpy --listen 0.0.0.0:5678 /usr/bin/odoo -c /etc/odoo/odoo.conf
    command: --dev=all --update=process_control #-i web_community

  postgres:
    image: postgres:15
    container_name: db_${CONTAINER_NAME}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${CONTAINER_USER}
      - POSTGRES_PASSWORD=${CONTAINER_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
#    ports:
#      - "5051:5432"
    # volumes:
    #   - postgres-odoo-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: pgadmin4:15
    container_name: pg_${CONTAINER_NAME}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${CONTAINER_PASSWORD}
    # volumes:
    #   - pgadmin-odoo-data:/var/lib/pgadmin
    restart: unless-stopped

# volumes:
#   odoo-data:
#     name: odoo-${VOLUMES_NAME}
#   postgres-odoo-data:
#     name: postgres-${VOLUMES_NAME}
#   pgadmin-odoo-data:
#     name: pgadmin-${VOLUMES_NAME}

# secrets:
#   postgresql_password:
#     file: odoo_pg_pass
