[options]
addons_path = /mnt/extra-addons;,/mnt/enterprise-addons
data_dir = /var/lib/odoo
admin_passwd = admin
; db_host = db
; db_port = 5432
; db_user = odoo
; db_password = odoo
; without_demo = all

; Configuración de desarrollo
dev_mode = reload, xml, qweb, assets
log_level = debug
log_handler = :DEBUG