# -*- coding: utf-8 -*-

import wzd_efficient_report
import wzd_production_by_hours
import wzd_efficiency_accomplish
import wzd_interruptions_by_section
import wzd_interruptions_by_line
import wzd_interruptions_by_machine
import wzd_prod_and_reg_amf
import wzd_interruptions_to_excel
import wzd_time_use_to_excel
import wzd_efficiency_cdt_excel_report
#import wdz_resume_time_frequency
import wdz_compliance_planned_efficiency
import wdz_compliance_planned_cdt
import wzd_machine_set_of_peaces
import wzd_bd_production_hours
import wzd_statistical_results
import wzd_production_rejection
import wdz_resume_time_frequency_n


