from . import turn
from . import turn_attendance
from . import machine_type
from . import machine
from . import productive_line
from . import productive_section
from . import interrution_type
from . import interruption
from . import tech_control
from . import productive_section_plan
from . import machine_set_of_peaces
from . import rejection
from . import rejection_amf
from . import rejection_mod1
from . import production_by_hours
#from . import db_production_connector
#from . import productive_section_lines
